sudo: required

language: php

php:
  - 5.6

services:
  - docker

before_install:
  - docker-compose -f docker-compose-travis.yml up -d
  - docker ps -a

script:
  - docker exec -it drupalsocial_web_1 drush -y site-install social --db-url=mysql://root:root@db:3306/social --account-pass=admin install_configure_form.update_status_module='array(FALSE,FALSE)'
  - docker exec -it drupalsocial_web_1 drush -y status
  - sh dev-scripts/unit-tests.sh
  - sh behatstability.sh
