version: "2"

services:
  web_scripts:
    build: docker_build/drupal8/travis
    volumes:
     - ./html:/var/www/html
     - ./vendor:/var/www/vendor
     - ./composer.json:/var/www/composer.json
     - ./composer.lock:/var/www/composer.lock
     - ./dev-scripts/:/root/dev-scripts
     - ./docker_build/drupal8/travis/:/root/travis
     - ./test-results/:/root/test-results
    environment:
     - DRUPAL_SETTINGS=travis
    network_mode: "bridge"
    container_name: social_web_scripts

  web:
    image: goalgorilla/drupal_social
    volumes:
     - ./html:/var/www/html
     - ./vendor:/var/www/vendor
     - ./composer.json:/var/www/composer.json
     - ./composer.lock:/var/www/composer.lock
     - ./dev-scripts/:/root/dev-scripts
    links:
     - db:db
    environment:
     - DRUPAL_SETTINGS=production
    ports:
     - "80"
    network_mode: "bridge"
    container_name: social_web

  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=social
    volumes:
     - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    network_mode: "bridge"
    container_name: social_db

  selenium:
    image: selenium/standalone-firefox:2.48.2
    links:
     - web:web
    ports:
     - "4444"
     - "5900"
    cap_add:
     - NET_ADMIN
     - NET_RAW
    network_mode: "bridge"
    container_name: social_selenium

  behat:
    build: docker_build/drupal8/travis
    volumes:
     - ./html/:/var/www/html
     - ./vendor:/var/www/vendor
     - ./composer.json:/var/www/composer.json
     - ./composer.lock:/var/www/composer.lock
     - ./dev-scripts/:/root/dev-scripts
     - ./travis_artifacts/:/root/travis_artifacts
     - ./html/profiles/contrib/social/tests/behat/:/root/behat
     - ./docker_build/drupal8/travis/:/root/travis
    links:
     - web:web
     - db:db
     - selenium:selenium
    environment:
     - DRUPAL_SETTINGS=production
    network_mode: "bridge"
    container_name: social_behat

volumes:
  db_data:
