version: "2"

services:
  web:
    image: goalgorilla/drupal_social
    links:
      - db:db
    ports:
      - "80"

  db:
    image: mysql:5.6
    environment:
       - MYSQL_ROOT_PASSWORD=root
       - MYSQL_DATABASE=social
    volumes_from:
      - db_data

volumes:
  db_data:
